### ISSUE TITLE
No SIM detected

### ISSUE THREAD

**Issue by ncarvalho99** [vacuumbeef/droidian-adaptation-vayu#1]
Hello,

After following all the steps i run the command sudo /usr/share/ofono/scripts/list-contexts and the return was [ /ril_0 ], so i went to SIM Connection settings and saw that the droidian was not detecting my SIM card, i changed the slots that the SIM was but it didn't work.

SIM is from CLARO BR

**Comment by vacuumbeef** [comment]
Hello.
For now only first slot works. And ril_0 is the first slot actually.
Sometimes for some reason yeah, it does not detect the sim. I guess you tried rebooting with sim in slot 1 without changing anything?
You can also try `sudo systemctl restart ofono`

**Comment by ncarvalho99** [comment]
After a few atempts i make it work, it's sad that i can't use a sdcard with droidian because slot 1 is where sdcard should be

**Comment by vacuumbeef** [comment]
> After a few atempts i make it work, it's sad that i can't use a sdcard with droidian because slot 1 is where sdcard should be

Look, you can do this:
edit `/etc/ofono/ril_subscription.conf`

change this:
```
[ril_0]
transport=binder:name=slot1
name=slot1
```
to this
```
[ril_0]
transport=binder:name=slot2
name=slot2
```
And the sim would work in the second slot, so you can put your sdcard in the first one.
One person tested it for a few days, looks like it works good. Though I think you need to mount sdcard by yourself.
I think it would be cool to set sim2 slot by default, but for now I have no knowledge of how to do it properly.
_____
Also you can even do this:
```
[ril_0]
transport=binder:name=slot1
name=slot1

[ril_1]
transport=binder:name=slot2
name=slot2
```

And both sim slots would work, but I had problems with that, so I don't recommend. Maybe only for testing.
